apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookkinder-dev
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bookkinder-backend:latest
          imagePullPolicy: Never
          env:
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: bookkinder-config
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookkinder-config
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bookkinder-config
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: bookkinder-config
                  key: DB_USERNAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bookkinder-config
                  key: DB_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookkinder-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 8000
