apiVersion: v1
kind: ConfigMap
metadata:
  name: bookkinder-config
  namespace: bookkinder-dev
data:
  APP_ENV: "local"
  APP_DEBUG: "true"
  BACKEND_URL: "http://bookkinder.local/api"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql" 
  DB_DATABASE: "bookkinder"
  DB_USERNAME: "root"
  DB_PORT: "3306"
