services:
    mysql-service:
        image: mysql:8.4
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-123456789}
            MYSQL_DATABASE: '${DB_DATABASE:-bookkinder}'
        ports:
            - "${DB_PORT:-3307}:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - dev-bookkinder-backend-network

    php-service:
        build:
            context: ./docker
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - dev-bookkinder-backend-network
        depends_on:
            - mysql-service

    nginx-service:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - php-service
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        networks:
            - dev-bookkinder-backend-network

networks:
    dev-bookkinder-backend-network:
        driver: bridge
        name: dev-bookkinder-backend-network

volumes:
    mysql_data:
        driver: local