services:
    php-service:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - dev-bookkinder-backend-network

networks:
    dev-bookkinder-backend-network:
        driver: bridge
        name: dev-bookkinder-backend-network
